apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-shop
  #namespace: mymusicspace

  name: mongo-shop-svc

spec:
  selector:
    app: mongo-shop
  
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  clusterIP: None