apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: shop-service
  name: shop-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: shop-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/compose-mynetwork: "true"
        io.kompose.service: shop-service
    spec:
      containers:
        - env:
            - name: EUREKA_SERVER
              value: http://discovery-service:8761/eureka/
          image: shop-service:latest
          name: shop-service
          ports:
            - containerPort: 8095
              hostPort: 8095
              protocol: TCP
      restartPolicy: Always
