apiVersion: v1
kind: PersistentVolume
metadata:
  #namespace: mymusicspace

  labels:
    app: mysql-auth
  name:  mysql-auth-pv
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql-auth
  #namespace: mymusicspace

  name: mysql-auth-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi