apiVersion: v1
kind: Service
metadata:
  #namespace: swagmed
  name: front-end-svc
  labels:
    app: front-end
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 5173
      targetPort: 5173
      nodePort: 30010
  selector:
    app: front-end
