apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mongodatashop
  name: mongodatashop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
