apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-music
  #namespace: mymusicspace

  name: mysql-music-svc

spec:
  selector:
    app: mysql-music
  
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  clusterIP: None