apiVersion: v1
kind: Service
metadata:
  namespace: mymusicspace
  name: eureka-np
  labels:
    app: discovery-service
spec:
  type: NodePort
  ports:
    - port: 8761
      name: discovery-service
  selector:
    app: discovery-service