apiVersion: apps/v1
kind: Deployment

metadata:
  name: mongo-express-deployment
  labels:
    app: mongo-express

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
          - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            value: rootuser
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            value: rootpass
          - name: ME_CONFIG_MONGODB_SERVER
            value: mongodb-service
        imagePullPolicy: Always


---
# Fa le veci dell'ingress
# external service di tipo LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  labels:
    app: mongo-express

spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000