services:


  mongoShopDB:
    image: mongo
    container_name: mongoShopDB
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodatashop:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    networks:
      - mynetwork


  #######################################
  # Mongo express
  #######################################

  # mongo-express-shop:
  #   image: mongo-express
  #   container_name: mongo-express-shop
  #   restart: always
  #   ports:
  #     - "8082:8081"
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
  #     - ME_CONFIG_MONGODB_SERVER=mongoShopDB

  #   depends_on:
  #     - mongoShopDB
  #   networks:
  #     - mynetwork


  #######################################
  # discovery-service
  #######################################

  discovery-service:
    container_name: discovery-service
    build:
      context: ../discovery-service
      dockerfile: Dockerfile
    image: discovery-service:latest
    ports:
      - "8761:8761"
    restart: always
    networks:
      - mynetwork


  #######################################
  # API GATEWAY
  #######################################

  api-gateway-service:
    container_name: api-gateway-service
    build:
      context: ../api-gateway-service
      dockerfile: Dockerfile
    image: api-gateway-service
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
    restart: always
    networks:
      - mynetwork


  #######################################
  # shop-service container
  #######################################

  shop-service:
    container_name: shop-service
    build:
      dockerfile: Dockerfile
    image: shop-service:latest
    ports:
      - "8095:8095"
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka/
    networks:
      - mynetwork
    depends_on:
      - discovery-service
      - mongoShopDB
    restart: always



volumes:
  mongodatashop:

networks:
  mynetwork:
    driver: bridge
