apiVersion: apps/v1
kind: StatefulSet
metadata:
  #namespace: mymusicspace

  name: discovery-service
spec:
  serviceName: discovery-service-svc
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    
    spec:
      restartPolicy: Always
      containers:
        - name: discovery-service
          image: aamshaegar/discovery-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
  podManagementPolicy: "Parallel"