version: '3.7'

services:

  mysqlAuthDB:
    image: mysql:8.0
    container_name: mysqlAuthDB
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: AuthDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - mysqldataauth:/var/lib/mysql
    restart: always
    networks:
      - mynetwork




  #######################################
  # discovery-service
  #######################################

  discovery-service:
    container_name: discovery-service
    build:
      context: Back-end/discovery-service
      dockerfile: Dockerfile
    image: discovery-service:latest
    ports:
      - "8761:8761"
    restart: always
    networks:
      - mynetwork


  #######################################
  # API GATEWAY
  #######################################

  api-gateway-service:
    container_name: api-gateway-service
    build:
      context: Back-end/api-gateway-service
      dockerfile: Dockerfile
    image: api-gateway-service
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
    restart: always
    networks:
      - mynetwork



  #######################################
  # auth-service container
  #######################################

  auth-service:
    container_name: auth-service
    build:
      dockerfile: Dockerfile
    image: auth-service:latest
    ports:
      - "8090:8090"
    networks:
      - mynetwork
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
      - api-gateway-service
    restart: always


volumes:
  mysqldataauth:

networks:
  mynetwork:
    driver: bridge