version: "4.25"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ricerca
      MYSQL_DATABASE: Taass_Db
      MYSQL_USER: aclm
      MYSQL_PASSWORD: ricerca_Taass
    ports:
      - 3306:3306
