apiVersion: v1
kind: StatefulSet
metadata:
  namespace: mymusicspace
  name: mongo-shop-db
  labels:
    app: mongo-shop-db
spec:
  serviceName: mongo-shop-db
  replicas: 1
  selector:
    matchLabels:
      app: mongo-shop-db
  template:
    metadata:
      labels:
        app: mongo-shop-db
    spec:
      containers:
        - name: mongo-shop-db
          imagePullPolicy: IfNotPresent
          image: mongo:7.0.4
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: rootuser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: rootpass
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongodatashop
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: mongodatashop
          persistentVolumeClaim:
            claimName: "mongo-shop-db-pvc"
