apiVersion: v1
kind: StatefulSet
metadata:
  namespace: mymusicspace
  name: eureka-deployment
spec:
  serviceName: discovery-service
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      restartPolicy: Always
      containers:
        - name: discovery-service
          image: discovery-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_SERVER_ADDRESS
              value: http://discovery-service:8761/eureka/
            - name: EUREKA_HOSTNAME
              value: ${HOSTNAME}.eureka
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
  podManagementPolicy: "Parallel"