apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-log
  #namespace: mymusicspace

  labels:
    app: mongo-log

spec:
  serviceName: mongo-log-svc
  replicas: 1
  selector:
    matchLabels:
      app: mongo-log
  
  template:
    metadata:
      labels:
        app: mongo-log
    spec:
      containers:
      - name: mongo-log
        imagePullPolicy: IfNotPresent
        image: mongo
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: rootuser
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: rootpass
      
        ports:
          - containerPort: 27017
        volumeMounts:
            - mountPath: /data/db
              name: mongo-log-data
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
        - name: mongo-log-data
          persistentVolumeClaim:
            claimName: "mongo-log-pvc"
