apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-chat
  #namespace: mymusicspace

  name: mongo-chat-svc

spec:
  selector:
    app: mongo-chat
  
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  clusterIP: None