server:
  port: 8080

spring:
  application:
    name: api-gateway-service
  
  cloud:
    loadbalancer:
      cache:
        enabled: false
    
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            max-age: 3600
            allowed-headers: "*"
            exposed-headers: "X-Get-Header"
      
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      
      routes:

        ## API-GATEWAY/api/patient
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/api/chat/**

        - id: music-service
          uri: lb://music-service
          predicates:
            - Path=/api/music/***

        - id: shop-service
          uri: lb://shop-service
          predicates:
            - Path=/api/shop/**

        - id: log-service
          uri: lb://log-service
          predicates:
            - Path=/api/log/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials
        - DedupeResponseHeader=Access-Control-Allow-Origin


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone:
        ${EUREKA_SERVER:http://eurekaservice:8761/eureka}

  instance:
    appname: api-gateway-service
    instanceId: api-gateway-service