spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: demo1
          uri: lb://demo1
          predicates:
            - Path=/demo1**
          # PER ACCEDERE, DA BROWSER ANDARE SU: http://localhost:8080/DEMO1/say

  application:
    name: api-gateway-service
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}