apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: mongoshopdb
  name: mongoshopdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongoshopdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/compose-mynetwork: "true"
        io.kompose.service: mongoshopdb
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: rootpass
            - name: MONGO_INITDB_ROOT_USERNAME
              value: rootuser
          image: mongo
          name: mongoshopdb
          ports:
            - containerPort: 27017
              hostPort: 27018
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: mongodatashop
      restartPolicy: Always
      volumes:
        - name: mongodatashop
          persistentVolumeClaim:
            claimName: mongodatashop
