version: '3.7'

services:


  #######################################
  # front-end-service container
  #######################################

  front-end-container:
    container_name: front-end-container
    build:
      dockerfile: Dockerfile
    image: front-end-container:latest
    networks:
      - mynetwork
    ports:
      - "5173:5173"
    restart: always


networks:
  mynetwork:
    driver: bridge
