apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-service
  
  template:
    metadata:
      labels:
        app: shop-service
    spec:
      containers:
        - name: shop-service
          image: aamshaegar/shop-service:1.0.0
          imagePullPolicy: Always
          ports: 
            - containerPort: 8093
          env:
            - name: EUREKA_SERVER
              value: http://discovery-service-0.discovery-service-svc:8761/eureka/
            - name: SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE
              value: "admin"
            - name: SPRING_DATA_MONGODB_AUTO_INDEX_CREATION
              value: "true"
            - name: SPRING_DATA_MONGODB_HOST
              value: "mongo-shop-svc"
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_USERNAME
              value: "rootuser"
            - name: SPRING_DATA_MONGODB_PASSWORD
              value: "rootpass"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "shopDB"
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              memory: "800Mi"
              cpu: "1000m"
