apiVersion: v1
kind: PersistentVolume
metadata:
  #namespace: mymusicspace
  labels:
    app: mysql-music
  name:  mysql-music-pv
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql-music
  #namespace: mymusicspace
  name: mysql-music-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi